### ISSUE TITLE
Binding.pry in code

### ISSUE THREAD

**Issue by Zanadar** [picatz/shodanz#7]
https://github.com/picatz/shodanz/blob/581342537ae4adac5e93764ac70357a41303687a/lib/shodanz/apis/rest.rb#L185 has some debugging code (a `binding.pry`).
Was that intentional?

**Comment by picatz** [comment]
Fixed in version [`1.0.4`](https://github.com/picatz/shodanz/releases/tag/v1.0.4)

**Comment by picatz** [comment]
Thanks @Zanadar 🎉 🤘
