### ISSUE TITLE
undefined method

### ISSUE THREAD

**Issue by Abo5** [picatz/shodanz#81]
/Users/qppn/.rvm/gems/ruby-3.2.2/gems/shodanz-2.0.6/lib/shodanz.rb:12:in `<top (required)>': undefined method `logger' for Async:Module (NoMethodError)

Async.logger.level = 4
     ^^^^^^^
        from <internal:/Users/qppn/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/Users/qppn/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/Users/qppn/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:40:in `require'
        from /Users/qppn/Desktop/Projects/shodan.rb:1:in `<main>'
<internal:/Users/qppn/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': cannot load such file -- shodanz (LoadError)
        from <internal:/Users/qppn/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from /Users/qppn/Desktop/Projects/shodan.rb:1:in `<main>'

**Comment by ioquatix** [comment]
`Async.logger` should be replaced by `Console.logger`.

**Comment by picatz** [comment]
👋 Hello @Abo5, thank you for reporting this issue! I will take a look at later this week. 

❤️ Thank you for the tip @ioquatix!

**Comment by picatz** [comment]
Should be fixed with [`v2.0.7`](https://rubygems.org/gems/shodanz/versions/2.0.7), but please let me know if that doesn't resolve the problem. 😄
